name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:        
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make Gradle Wrapper script executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

  test-job1:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - name: Run Test Job 1
      run: |
        echo "Running Test Job 1..."
        ./gradlew test --tests 'com.example.devops_uppg_3.DevopsUppg3ApplicationTests'

  test-job2:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - name: Run Test Job 2
      run: |
        echo "Running Test Job 2..."
        ./gradlew test --tests 'com.example.devops_uppg_3.TodoControllerTest'

  test-job3:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - name: Run Test Job 3
      run: |
        echo "Running Test Job 3..."
        ./gradlew test --tests 'com.example.devops_uppg_3.TodoServiceTest'
