name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:        
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make Gradle Wrapper script executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        
    - name: Run Unit Tests
      run: |
        echo "Running Unit Tests..."
        gradle test --tests 'DevopsUppg3ApplicationTests.java'
        gradle test --tests 'TodoControllerTest.java'
        gradle test --tests 'TodoServiceTest.java'
